install.packages("targets")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("medicaldata")
install.packages("visNetwork")
library(targets)
library(ggplot2)
library(dplyr)
library(medicaldata)
library(visNetwork)
tar_script()
tar_visnetwork()

library(medicaldata)
write.csv(medicaldata::supraclavicular, "data/supraclavicular.csv", row.names = FALSE)
df <- read.csv("data/supraclavicular.csv")
View(df)